### PR TITLE
23.10-1595145.22.04

### PR DESCRIPTION
**Pull request by emaxoda**
it needs linux-firmware-git but once it lands on the arch repos it should work out of the box

### CODE REVIEW

**Comment by mesmerx** [comment]
it needs a little bit more update, because of unmapped/wrong mapped rep, i am working o that right now, but thx for the PR

**Comment by mesmerx** [comment]
this is the PR https://github.com/Ashark/archlinux-amdgpu-pro/pull/88

**Comment by mesmerx** [comment]
about the linux-firmware, with git its working for 7000 series?

**Comment by mesmerx** [comment]
https://github.com/Ashark/archlinux-amdgpu-pro/issues/85 if you can please put your tests there too

**Comment by emaxoda** [comment]
I don't own an 7000 series but AMF asked for newer firmware or it wouldn't initialize.

**Comment by mesmerx** [comment]
same here, i think the newest driver needs firmware-git maybe i add as a dependency

**Pull request closed without merging**
